# Generated by Django 5.1.6 on 2025-02-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='gives_free_premium',
        ),
    ]
