# Generated by Django 5.1.6 on 2025-02-21 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_remove_coupon_gives_free_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller_coupon', to='authentication.seller'),
            preserve_default=False,
        ),
    ]
